# Generated by Django 2.2.5 on 2022-01-10 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('time', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.GoodsCategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '分类浏览次数',
                'verbose_name_plural': '分类浏览次数',
                'db_table': 'tb_visit',
            },
        ),
    ]
