# Generated by Django 2.2.5 on 2022-01-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_auto_20220112_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('trade_id', models.CharField(max_length=100, verbose_name='支付流水号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.OrderInfo', verbose_name='订单')),
            ],
            options={
                'verbose_name': '支付信息',
                'verbose_name_plural': '支付信息',
                'db_table': 'tb_payment',
            },
        ),
    ]
